services:
  postgres:
    image: postgres:18
    container_name: corporate-file-processor-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: corporate_file_processor
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: